mongodb:
    image: mongo:2.6
    hostname: mongodb
    container_name: mongodb
    expose:
        - "27017"
    ports:
        - "27017:27017"
    command: --smallfiles

orion:
    image: fiware/orion:latest
    hostname: orion
    container_name: orion
    links:
        - mongodb
    expose:
        - "1026"
    ports:
        - "1026:1026"
    command: -dbhost mongodb

mysql:
    image: mysql:5.5
    hostname: mysql
    container_name: mysql
    expose:
        - "3306"
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=mysql

proton:
    image: fiware/proactivetechnologyonline:latest
    hostname: proton
    container_name: proton
    expose:
        - "8080"
    ports:
        - "8080:8080"

spagobi:
    image: spagobilabs/spagobi:all-in-one
    hostname: spagobi
    container_name: spagobi
    links:
        - spagobidb:db
    ports:
        - "8082:8080"
    environment:
        - WAIT_MYSQL=true

spagobidb:
    image: mysql:5.5
    hostname: spagobidb
    container_name: spagobidb
    environment:
        - MYSQL_USER=spagobiuser
        - MYSQL_PASSWORD=spagobipassword
        - MYSQL_DATABASE=spagobidb
        - MYSQL_ROOT_PASSWORD=spagobirootpassword

cygnus:
    image: fiware/cygnus-ngsi:latest
    hostname: cygnus
    container_name: cygnus
    links:
        - orion
        - mysql:iot-mysql
    expose:
        - "5050"
        - "8081"
    ports:
        - "5050:5050"
        - "8081:8081"
    environment:
        - CYGNUS_USER=cygnus
        - CYGNUS_HOME=/opt/fiware-cygnus
        - CYGNUS_VERSION=1.6.0_SNAPSHOT

        - CYGNUS_CONF_PATH=/opt/apache-flume/conf
        - CYGNUS_CONF_FILE=/opt/apache-flume/conf/agent.conf

        - CYGNUS_AGENT_NAME=cygnus-ngsi

        - CYGNUS_LOG_LEVEL=DEBUG
        - CYGNUS_LOG_APPENDER=console

        - CYGNUS_SERVICE_PORT=5050
        - CYGNUS_API_PORT=8081

        - CYGNUS_MYSQL_HOST=iot-mysql
        - CYGNUS_MYSQL_PORT=3306
        - CYGNUS_MYSQL_USER=root
        - CYGNUS_MYSQL_PASS=mysql

        - CYGNUS_MONGO_HOSTS=mongodb:27017
        - CYGNUS_MONGO_USER=mongo
        - CYGNUS_MONGO_PASS=mongo

        - CYGNUS_CKAN_HOST=81.14.183.132
        - CYGNUS_CKAN_PORT=80
        - CYGNUS_CKAN_API_KEY=73ff0a43-80d8-4439-bdeb-43294432fa0c
        - CYGNUS_CKAN_SSL=false

        - CYGNUS_HDFS_HOST=storage.cosmos.lab.fiware.org
        - CYGNUS_HDFS_PORT=14000
        - CYGNUS_HDFS_USER=gernotgbbsboege
        - CYGNUS_HDFS_TOKEN=aHWab78WuncyYscTmTCZqYZ5zkcfWD
